name: mdbook
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: |
          cargo install mdbook
          cargo install mdbook-force-relative-links
          cargo install mdbook-admonish
          cargo install mdbook-tailor
          cargo install mdbook-embedify
      - run: mdbook build
      - uses: peaceiris/actions-gh-pages@v4
        with:
        	github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book
          publish_branch: gh-pages

